// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Verifies that the service can reach its database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "503": {
                        "description": "Database unavailable",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Returns the identifiers of all users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-array_string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a user from the provided credentials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/communication.UserDtoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_UserDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user syntax, email, or password",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "409": {
                        "description": "Email already in use",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/users/auth": {
            "get": {
                "description": "Validates the API key provided in the request header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-Api-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "403": {
                        "description": "User is not authenticated",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/users/sessions": {
            "post": {
                "description": "Authenticates a user with email and password and returns an API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create session",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/communication.UserDtoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_ApiKeyDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user syntax",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "No such user",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/users/sessions/{id}": {
            "delete": {
                "description": "Revokes the active session for the specified user.",
                "tags": [
                    "sessions"
                ],
                "summary": "Delete session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "No such user",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Returns a user by its identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_UserDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "No such user",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a user identified by its identifier.",
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid id syntax",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates a user identified by its identifier.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/communication.UserDtoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-communication_UserDtoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id or user syntax",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "404": {
                        "description": "No such user",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "409": {
                        "description": "User is not up to date",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseEnvelope-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "communication.ApiKeyDtoResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "format": "uuid",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                },
                "user": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "validUntil": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-04-28T20:56:59Z"
                }
            }
        },
        "communication.UserDtoRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePassword123"
                }
            }
        },
        "communication.UserDtoResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-04-27T20:56:59Z"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePassword123"
                }
            }
        },
        "rest.ResponseEnvelope-array_string": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_ApiKeyDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.ApiKeyDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-communication_UserDtoResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/communication.UserDtoResponse"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.ResponseEnvelope-string": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.Status"
                        }
                    ],
                    "example": "SUCCESS"
                }
            }
        },
        "rest.Status": {
            "type": "string",
            "enum": [
                "SUCCESS",
                "ERROR"
            ],
            "x-enum-varnames": [
                "StatusSuccess",
                "StatusError"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Api-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "User Service API",
	Description:      "HTTP API for managing users, sessions, and API key authentication.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
